### PR TITLE
Linting2

### PR DESCRIPTION
**Pull request by howetuft**
This PR aims at improving code quality, with no added functionality. The goal is to make code more readable, maintainable and extendable.
It mainly enforces PEP8 and PEP 257 on existing files, but beyond that, an attempt was sometimes also made to make code more "pythonic" (use of language idioms: list comprehensions, context managers, format specification mini-language...).
In detail:

- Lint code
    - Run pylint and flake8, and correct warnings/errors emitted whenever possible: lines too long, unused variables, naming rules violations, imports position in file and order, max number of statements in functions/methods, blank lines rules violation etc.
    - Add docstrings wherever required
    - Add a 'pylintrc' file for subsequent use
    - Add a mention about code quality ambition in README.md
    - Add some additional comments
    - Add a license file

- Improve code pythonicity
    - Use context managers for file operations
    - Use python format specification mini-language in lieu of (more cumbersome) concatenation, in external renderers modules
    - Use idioms (list comprehensions, expression generators, ternary operator...) wherever relevant

- Make some refactoring:
    - Create a RendererHandler class to simplify interactions with external renderers modules (façade design pattern), also to reduce number of statements in Project.render()
    - Create factory methods for Project, View and Camera objects
    - Remove (previously empty) License section in README.md and add a LICENCE file instead (LGPL2, directly copied from FreeCAD directory)
    - Provide a default camera even if GUI is down (in case it is used in console mode)

**2nd try: modifications have been split into several progressive commits for easier reviewing and maintenance...**

### CODE REVIEW

**Comment by luzpaz** [comment]
Nice! Thanks for doing that :+1:

**Comment by howetuft** [comment]
@yorikvanhavre Hello! Just in case you did not see this PR: it is the same as my previous one (#29, which I eventually closed), but with progressive detailed commits.
Thank you for your feedback!

**Comment by luzpaz** [comment]
@yorikvanhavre bump

**Comment by yorikvanhavre** [comment]
Nice job!! Thanks!

**Comment by howetuft** [comment]
Thank you!

Le jeu. 12 mars 2020 à 13:35, Yorik van Havre <notifications@github.com> a
écrit :

**Pull request merged**
