### PR TITLE
LuxCore: add library path

### PR DESCRIPTION
**Pull request by jphigham**
Added pref for LuxCore library path to enable launch under AppImage

### CODE REVIEW

**Comment by howetuft** [comment]
Hello,
Thank you for your contribution!
Unfortunately, I was simultaneously doing some heavy work on renderers execution code, so your PR eventually conflicts a lot (for instance, POpen is no more in renderer plugin, but in a new common class dedicated for renderer execution...).
However, I have some ideas to integrate your proposition into new code and there is some of kind of basis in your code I can reuse, so I'm going to merge your PR **_partially_**, and write some complementary code to get it work, if you don't mind.

**Comment by jphigham** [comment]
No problem! I made the PR only because I couldn't find a graceful way to launch LuxCore from FreeCAD inside the AppImage restricted environment and thought others might find it helpful. Not sure whether similar needs will arise for the other renderers. When I have a chance I'll try some. Great workbench!

**Comment by jphigham** [comment]
btw, I realized later there should be a check for adding the LuxCore lib path to an already-set LD_LIBRARY_PATH

**Comment by howetuft** [comment]
Note that you may have a direct solution prefixing your call to LuxCore with an `env` command, in `LuxCore UI path`. For instance:

`env LD_LIBRARY_PATH=<your_lib_path> /usr/bin/luxcoreui`

But allowing user to easily provide some environment variables appears a good idea to me (especially for Appleseed).

Please note I'm gonna revert the commit in 'master' branch. I've imported it to my own work branch, and while I work on it, I'll leave the master code in a consistent state. I'll 'unrevert' at the end.

**Comment by jphigham** [comment]
> Note that you may have a direct solution prefixing your call to LuxCore with an `env` command, in `LuxCore UI path`. For instance:
> 
> `env LD_LIBRARY_PATH=<your_lib_path> /usr/bin/luxcoreui`
> 
> But allowing user to easily provide some environment variables appears a good idea to me (especially for Appleseed).
> 
> Please note I'm gonna revert the commit in 'master' branch. I've imported it to my own work branch, and while I work on it, I'll leave the master code in a consistent state. I'll 'unrevert' when I'm done.

That works perfectly! I thought I had tried that while searching for a solution, but must not have had the command line syntax correct. Feel free to disregard this PR - sorry for the distraction!

**Comment by howetuft** [comment]
OK, so I close this PR, but I'll keep it in mind for future features.

**Pull request merged**
