### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.ts,*.oso -L sur`

### CODE REVIEW

**Comment by luzpaz** [comment]
Please review 9d044a2 closely

**Comment by howetuft** [comment]
Hello @Luzpaz,
Your PR I cannot merge, unfortunately: mispelling comes from upstream, see documentation https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.5#Light_emission, and Render WB must stick to that.

But it allows me to appreciate how tenacious you are: https://github.com/FreeCAD/FreeCAD-render/pull/119#issuecomment-777759306 :smiley:

**Comment by howetuft** [comment]
Update:
My previous post was about 9d044a2. f623042 is perfectly ok!
So, can you please revert 9d044a2? Then I shall merge.
Thanks in advance!

**Comment by luzpaz** [comment]
I've asked upstream to consider deprecating that function, breaking API sucks so they may not go for it. Nevertheless, I've reverted the offending commit. Cheers!

**Comment by howetuft** [comment]
Done, thank you!

**Comment by luzpaz** [comment]
Just a heads up that upstream has fixed some source typos, see https://github.com/LuxCoreRender/LuxCore/pull/575#issuecomment-1019134636

**Comment by luzpaz** [comment]
Upstream has made changes
https://github.com/LuxCoreRender/LuxCore/commit/92e98a4aa96518fa9d62676b7bea10b73d24ed42

**Comment by howetuft** [comment]
Congrats!
However, for now, it's just in the devel branch, so I shall wait for their next release to correct Render WB (I think it will be 2.7), otherwise we would be in danger of breaking the compatibility with the official version.
In the meantime, I will still fix some local variables not directly related to the API, in anticipation.

**Pull request merged**
