### PR TITLE
Appleseed: fix unescaped '\t' in mesh temp file path

### PR DESCRIPTION
**Pull request by howetuft**
Fix issue #30

### CODE REVIEW

**Comment by luzpaz** [comment]
@yorikvanhavre bump

**Comment by howetuft** [comment]
@yorikvanhavre Hello ! Just in case you did not notice my PR...

Moreover, as I know you must be quite busy: do you think it would be acceptable that you grant me (or perhaps someone else) write access to FreeCAD-render repository? Thanks in advance...

**Comment by yorikvanhavre** [comment]
Sorry guys, I was in the middle of escaping coronavirus airport blockings! Now safe and sound in european quarantaine ;)

**Comment by howetuft** [comment]
Hi Yorik,
Welcome back, and glad to find you well!
Thank you for your merging, by the way!!!

**Pull request merged**
